# Generated by Django 4.1.1 on 2022-09-11 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_author_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.post'),
        ),
    ]
