# Generated by Django 4.1.1 on 2022-09-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
