# Generated by Django 4.1.1 on 2022-09-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_comment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_test',
            new_name='comment_text',
        ),
    ]
